apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'zozo@z0z0.tk'
    provateKeySecretRef:
      name: letsencrypt-prod
    http01: {}